---
apiVersion: v1
kind: Namespace
metadata:
  name: ebpf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "ebpf-svc-acc"
  namespace: ebpf
  labels:
    app: agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "ebpf-svc-acc-role"
  namespace: ebpf
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "ebpf-svc-acc"
  namespace: ebpf
roleRef:
  kind: ClusterRole
  name: "ebpf-svc-acc-role"
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: "ebpf-svc-acc"
    namespace: ebpf
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent
  namespace: ebpf
  labels:
    app: agent
spec:
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      name: agent
      labels:
        app: agent
    spec:
      serviceAccountName: "ebpf-svc-acc"
      containers:
        - image: ebpf:latest
          imagePullPolicy: IfNotPresent
          name: agent
          command:
            - "/agent"
          volumeMounts:
            - name: sys-fs
              mountPath: /sys/fs
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: true
          securityContext:
            privileged: true
      hostNetwork: true
      hostPID: true
      volumes:
        - name: sys-fs
          hostPath:
            path: /sys/fs
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock